steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "DB_USER=${_DB_USER}"
      - "DB_PASS=${_DB_PASS}"
      - "STRIPE_SECRET=${_STRIPE_SECRET}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
